### PR TITLE
start creating user signup and login authentication system 

### PR DESCRIPTION
**Pull request by vijay-jadhav1997**
#### 🛠 I made following changes:

1. Created two View Classes in view.py file, namely UserSignupView and UserLoginView.
2.  Added tow template files, namely user_signup.html and user_login.html
3.  Styled both user_signup.html and user_login.html

#### My creation demo:

https://github.com/tukoba-dnyanoba1275/Django-Projects/assets/144908610/584fe478-1d6c-48b3-ab24-37243565809b

### CODE REVIEW

**Comment by vijay-jadhav1997** [comment]
###  Please suggest any changes and ideas for improvements regarding:
-  Layout
- Style
- Feature
- .........

**Comment by tukoba-dnyanoba1275** [comment]
### logout facility is missing, please add logout feature.

**Comment by vijay-jadhav1997** [comment]
> ### logout facility is missing, please add logout feature.

Yes, I'm currently working on that feature.

**Comment by tukoba-dnyanoba1275** [comment]
ok.

**Comment by tukoba-dnyanoba1275** [comment]
We want to convert this crud app to school app. So we close this issue now.

**Pull request merged**
